CREATE TABLE IF NOT EXISTS "RuntimeSetting" (
  "key" TEXT PRIMARY KEY,
  "value" TEXT NOT NULL,
  "isSecret" BOOLEAN NOT NULL DEFAULT false,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
